version: "3.9"
services:
  bidx-ai-db:
    image: postgres
    restart: always
    container_name: bid-ai-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: